site_name: whk-space
site_url: https://lumo-org.github.io/whk-space

# Repository.
repo_name: lumo-org/whk-space
repo_url: https://github.com/lumo-org/whk-space

# Contents.
nav:
  - README:
    - README.md
    - CONTRIBUTING: CONTRIBUTING.md
  - 数列:
    - sequence/index.md
    - 等差数列重要公式: sequence/AP-formula.md
    - 等差-等比数列: sequence/A-GP.md
  - 微分:
    - differential/index.md
  - Main Site: https://lumo-org.github.io/

# Theme.
theme:
  name: material
  # i18n.
  language: zh
  # Color palette.
  palette:
    # Palette toggle for light mode.
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      toggle:
        icon: material/lightbulb
        name: 切换到深色模式.

    # Palette toggle for dark mode.
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/lightbulb-outline
        name: 切换到浅色模式.
  # Font configuration (Google Fonts).
  font:
    text: Roboto
    code: Roboto Mono
  # Site logo.
  icon:
    logo: material/draw-pen
  # Features.
  features:
    # This feature flag is not compatible with toc.integrate, 
    # as sections cannot host the table of contents due to missing space.
    - navigation.indexes
    - navigation.tabs

# Plugins.
plugins:
  - search
  - git-authors:
      show_contribution: true

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://mirrors.sustech.edu.cn/cdnjs/ajax/libs/mathjax/3.2.2/es5/tex-mml-chtml.min.js
