site_name: whk-space
site_url: https://lumo-org.github.io/whk-space

# Repository.
repo_name: lumo-org/whk-space
repo_url: https://github.com/lumo-org/whk-space

# Contents.
nav:
  - README:
    - README.md
    - CONTRIBUTING: CONTRIBUTING.md
  - 圆锥曲线:
    - conic-section/index.md
    - 曲线系: conic-section/system-of-curves.md
    - 从零开始掌握圆锥曲线大法——上: conic-section/conic_section_brilliant11001.md
  - 数列:
    - sequence/index.md
    - 等差数列重要公式: sequence/AP-formula.md
    - 等差-等比数列: sequence/A-GP.md
  - 高等数学:
    - fur-math/index.md
    - 面向高中生の洛必达法则简述: fur-math/l-hopital-rule-introduction.md
  - 线性代数:
    - linear-algebra/index.md
    - 矩阵行列式瞬秒立体图形体积计算: linear-algebra/determinant-and-volume.md
  - 扩展:
    - extended/index.md
    - 奇技淫巧:
      - 路径组合计数问题的线性递推解法: extended/tricks/dp-in-math-combination.md

  - Main Site: https://lumo-org.github.io/

# Theme.
theme:
  name: material
  custom_dir: overrides
  # i18n.
  language: zh
  # Color palette.
  palette:
    # Palette toggle for light mode.
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      toggle:
        icon: material/lightbulb
        name: 切换到深色模式.

    # Palette toggle for dark mode.
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/lightbulb-outline
        name: 切换到浅色模式.
  # Font configuration (Google Fonts).
  font:
    text: Roboto
    code: Roboto Mono
  # Site logo.
  icon:
    logo: material/draw-pen
  # Features.
  features:
    # This feature flag is not compatible with toc.integrate, 
    # as sections cannot host the table of contents due to missing space.
    - navigation.indexes
    - navigation.tabs
# Comment
custom_dir: docs/overrides

# Plugins.
plugins:
  - search
  - git-authors:
      show_contribution: true

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tilde

extra_javascript:
  - javascripts/mathjax.js
  - https://mirrors.sustech.edu.cn/cdnjs/ajax/libs/mathjax/3.2.2/es5/tex-mml-chtml.min.js
