site_name: whk-space
site_url: https://lumo-org.github.io/whk-space

nav:
  - index.md
  - Section 1:
    - section1/index.md
    - Page 1: section1/page-1.md

theme:
  name: material
  # i18n.
  language: zh
  # Color palette.
  palette:
    # Palette toggle for light mode.
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      toggle:
        icon: material/lightbulb
        name: 切换到深色模式.

    # Palette toggle for dark mode.
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/lightbulb-outline
        name: 切换到浅色模式.
  # Font configuration (Google Fonts).
  font:
    text: Roboto
    code: Roboto Mono
  # Site logo.
  icon:
    logo: material/draw-pen
  # Features.
  features:
    # This feature flag is not compatible with toc.integrate, 
    # as sections cannot host the table of contents due to missing space.
    - navigation.indexes 

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://mirrors.sustech.edu.cn/cdnjs/ajax/libs/mathjax/3.2.2/es5/tex-mml-chtml.min.js